Boolean Arrays

In [1]:
import numpy as np
import sys
a=np.arange(4)

In [2]:
a

array([0, 1, 2, 3])

In [5]:
a[0],a[-1]

(0, 3)

In [6]:
a[[True,False,False,True]]

array([0, 3])

In [7]:
a>=2

array([False, False,  True,  True])

In [8]:
a[a>=2]

array([2, 3])

In [9]:
a.mean()

1.5

In [10]:
a[a>=a.mean()]

array([2, 3])

In [12]:
a[~(a>=a.mean())]
#negation

array([0, 1])

In [16]:
a[(a==0) | (a==1)]

array([0, 1])

In [17]:
a[(a>1) & (a<=4)]

array([2, 3])

In [20]:
A=np.random.randint(100,size=(3,3))

In [21]:
A

array([[79, 79, 42],
       [98, 85, 47],
       [14, 47, 53]])

In [22]:
A[np.array(
    [
     [True,False,False],
     [False,True,False],
     [False,False,True]
    ]
)]

array([79, 85, 53])

In [24]:
A>=20

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

array([18, 13, 11, 14, 11, 16, 15, 11, 14, 15, 11, 18])

In [25]:
A[A>20]

array([79, 79, 42, 98, 85, 47, 47, 53])