NumPy exercises

In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


Array creation

Create a numpy array of size 10, filled with zeros.

In [ ]:
zeros_array=np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a numpy array with values ranging from 10 to 49

In [2]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a numpy matrix of 2*2 integers, filled with ones.

In [3]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

Create a numpy matrix of 3*2 float numbers, filled with ones.

In [4]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [5]:
X=np.arange(4,dtype=int)
np.ones_like(X)

array([1, 1, 1, 1])

Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [6]:
X=np.arange(1,10,dtype=int).reshape((3,3))
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

 Create a numpy matrix of 4*4 integers, filled with fives.

In [7]:
np.ones((4,4),dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

 Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [8]:
X=np.arange(1,10,dtype=int).reshape(3,3)
np.ones_like(X)*7

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.


In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a numpy array, filled with 3 random integer values between 1 and 10.

In [11]:
np.random.randint(10,size=(3,3))

array([[9, 6, 2],
       [8, 7, 1],
       [6, 6, 3]])

Create a 3*3*3 numpy matrix, filled with random float values.

In [ ]:
  np.random.randn(3,3,3)

array([[[-0.69858745,  1.68050139,  1.33234159],
        [ 0.2815834 ,  0.45401906, -0.1273878 ],
        [-0.36134355, -0.01609611,  0.03265634]],

       [[ 0.32794559, -0.4078568 ,  0.26807182],
        [ 0.47917963, -0.87410483,  1.03915125],
        [-0.25201292,  1.05638045,  0.25500894]],

       [[ 0.31006197, -0.5452307 ,  0.59033275],
        [ 0.37622071,  1.0792398 ,  0.50125942],
        [-0.234051  ,  1.91377427, -0.27540846]]])

 Given the X python list convert it to an Y numpy array

In [12]:
X=list(range(10))
print(type(X))
Y=np.array(X)
print(type(Y))
Y

<class 'list'>
<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Given the X numpy array, make a copy and store it on Y.

In [13]:
X=np.random.randn(3,3)
Y=np.copy(X)
print(Y,id(Y)) #different id but same contetnt
print(X,id(X))

[[ 0.54515166 -0.75086435  2.16582031]
 [ 0.29240711 -0.74185008  1.54811203]
 [ 0.42273547  1.58372426 -0.37662675]] 140501699744352
[[ 0.54515166 -0.75086435  2.16582031]
 [ 0.29240711 -0.74185008  1.54811203]
 [ 0.42273547  1.58372426 -0.37662675]] 140501699745392


Create a numpy array with numbers from 1 to 10

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Create a numpy array with the odd numbers between 1 to 10

In [15]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

Create a numpy array with numbers from 1 to 10, in descending order.

In [16]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [17]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Show the memory size of the given Z numpy matrix

In [18]:
np.arange(0,9).reshape((3,3)).itemsize

8

Array indexation

Given the X numpy array, show it's first element

In [19]:
np.random.randint(20,size=10)[0]

16

Given the X numpy array, show it's last element

In [20]:
np.random.randint(20,size=10)[-1]

13

 Given the X numpy array, show it's first three elements

In [21]:
np.arange(1,11).reshape(10)[0:3]

array([1, 2, 3])

Given the X numpy array, show all middle elements

In [22]:
np.arange(1,11).reshape(10)[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

Given the X numpy array, show the elements in reverse position

In [23]:
np.arange(1,11).reshape(10)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

Given the X numpy array, show the elements in an odd position

In [26]:
np.arange(1,11).reshape(10)[::2]

array([1, 3, 5, 7, 9])

Given the X numpy matrix, show the first row elements

In [27]:
np.arange(1,10).reshape(3,3)[0]

array([1, 2, 3])

Given the X numpy matrix, show the last row elements

In [28]:
np.arange(1,10).reshape(3,3)[-1]

array([7, 8, 9])

Given the X numpy matrix, show the first element on first row

In [29]:
np.arange(1,10).reshape(3,3)[0,0]

1

Given the X numpy matrix, show the middle row elements

In [30]:
np.arange(1,10).reshape(3,3)[1:-1]

array([[4, 5, 6]])

Given the X numpy matrix, show the first two elements on the first two rows

In [31]:
A=np.arange(1,10).reshape(3,3)
print(A)
print(A[:2,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


Given the X numpy matrix, show the last two elements on the last two rows

In [ ]:
print(A)
print(A[1:3,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

Array manipulation

Convert the given integer numpy array to float

In [32]:
X=np.random.randint(1,100,size=20,dtype=int)
Y=np.array(X,dtype=float)
Y

array([ 7., 36., 32., 63., 90., 33., 93., 55., 68., 35., 89., 48., 45.,
       72., 83., 16., 42., 25., 52., 89.])

Reverse the given numpy array (first element becomes last)

In [33]:
np.random.randint(1,50,size=25,dtype=int)[::-1]

array([ 6,  7, 14, 12, 30, 30, 29, 22, 24, 18,  1,  2, 16,  2, 23, 27, 44,
       48, 39, 29, 16, 22, 37, 23,  1])

Order (sort) the given numpy array

In [34]:
A=np.random.randint(1,50,size=25,dtype=int)
print(A)
A.sort()
print(A)


[24 17 15 45 31 18 15 10 25 18 40  2 31 17 41 43 14 32 20  1  3 28 41  4
 35]
[ 1  2  3  4 10 14 15 15 17 17 18 18 20 24 25 28 31 31 32 35 40 41 41 43
 45]


Given the X numpy array, set the fifth element equal to 1

In [35]:
A=np.arange(10)
print(A)
A[4]=1
print(A)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 1 5 6 7 8 9]


Given the X numpy array, change the 50 with a 40

In [36]:
X=np.array([10,20,30,40,50,80])
X[X==50]=40
X

array([10, 20, 30, 40, 40, 80])

Given the X numpy matrix, change the last row with all 1

In [37]:
A=np.random.randint(1,10,size=(3,3),dtype=int)

print(A,"\n")

A[2]=1
print(A)


[[7 9 7]
 [9 5 7]
 [5 6 2]] 

[[7 9 7]
 [9 5 7]
 [1 1 1]]


Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
A[2,2]=0
A

array([[1, 7, 4],
       [2, 6, 5],
       [1, 1, 0]])

Given the X numpy matrix, add 5 to every element

In [ ]:
A=np.random.randint(1,10,size=(3,3),dtype=int)+5
A

array([[ 8,  6,  7],
       [13,  6,  6],
       [ 7, 12, 14]])

Boolean arrays (also called masks)

Given the X numpy array, make a mask showing negative elements

In [ ]:
X=np.array(
    [-9,-1,7,1,2,3,4,-4]
)
[X<0]

[array([ True,  True, False, False, False, False, False,  True])]

Given the X numpy array, get the negative elements

In [ ]:
X=np.array(
    [-9,-1,7,1,2,3,4,-4]
)
X[X<0]


array([-9, -1, -4])

Given the X numpy array, get numbers higher than 5

In [ ]:
X=np.array(
    [-9,-1,7,1,2,8,19,4,-4]
)
X[X>5]

array([ 7,  8, 19])

Given the X numpy array, get numbers higher than the elements mean

In [ ]:
X=np.array(
    [-9,-1,7,1,2,8,19,4,-4]
)
print(X[X>X.mean()])
print(X.mean())

[ 7  8 19  4]
3.0


Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
X=np.array(
    [-9,-1,2,1,2,8,10,4,-4]
)
X[(X==2) | (X==10)]

array([ 2,  2, 10])

Logic functions

Given the X numpy array, return True if none of its elements is zero

In [ ]:
X=np.array(
    [-9,-1,2,1,2,8,10,4,-4]
)
X.all()

True

Given the X numpy array, return True if any of its elements is zero

In [ ]:
X.any()

True

Summary statistics
Given the X numpy array, show the sum of its elements

In [ ]:
print(X)
print(X.sum())

[-9 -1  2  1  2  8 10  4 -4]
13


Given the X numpy array, show the mean value of its elements

In [ ]:
print(X)
print(X.mean())

[-9 -1  2  1  2  8 10  4 -4]
1.4444444444444444


Given the X numpy matrix, show the sum of its columns

In [ ]:
A=np.arange(1,10,dtype=int).reshape(3,3)
print(A)
A.sum(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

Given the X numpy matrix, show the mean value of its rows

In [ ]:
print(A)
print(A.mean(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2. 5. 8.]


Given the X numpy array, show the max value of its elements

In [ ]:
np.random.randint(0,1000,size=500,dtype=int).max()


999