In [1]:
import numpy as np
import sys

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a=np.array([1,2,3,4])

In [4]:
a[0],a[1]

(1, 2)

In [5]:
a[0:]

array([1, 2, 3, 4])

In [6]:
a[::-1]

array([4, 3, 2, 1])

In [7]:
b=np.array([0,0.5,1,1.5,2])

Array Types

In [8]:
a

array([1, 2, 3, 4])

In [9]:
a.dtype

dtype('int64')

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b.dtype

dtype('float64')

In [12]:
np.array([1,2,3,4],dtype=np.float)

array([1., 2., 3., 4.])

In [13]:
np.array([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [14]:
c=np.array(['a','b','c'])
c.dtype


dtype('<U1')

In [15]:
A=np.array(
    [
      [1,2,3],
      [4,5,6]   
    ]
)

In [16]:
A.shape

(2, 3)

In [17]:
A.size

6

In [18]:
A.ndim

2

Indexing and seraching elements in numpy matrix

In [22]:
A=np.array(
    [
     #0 1 2
     [1,2,3], # 0
     [4,5,6], # 1
     [7,8,9]  #2
    ]
)


In [23]:
A[1]

array([4, 5, 6])

In [24]:
A[1][0]

4

In [25]:
A[1,0]

4

In [26]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [28]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
A[0]=np.array([10,11,12])

In [30]:
A

array([[10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

Summary Statistics

In [31]:
a=np.array([1,2,3,4])

In [32]:
a.sum()

10

In [33]:
a.mean()

2.5

In [34]:
a.std()

1.118033988749895

In [35]:
a.var()

1.25

In [36]:
A

array([[10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [37]:
A.sum()

72

In [38]:
A.sum(axis=0)
#col sum

array([21, 24, 27])

In [39]:
A.sum(axis=1)
#row sum

array([33, 15, 24])

In [40]:
A.var()

6.666666666666667

In [41]:
A.std()

2.581988897471611

In [42]:
A.sum(axis=0)

array([21, 24, 27])

In [43]:
A

array([[10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [44]:
A.mean(axis=0)

array([7., 8., 9.])

In [45]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [66]:
B=np.array(
    
     [
      [1,2,3],
      [4,5,6],
      [7,8,9] 
     ],  dtype=int
    
)

In [56]:
B.ndim

2

In [57]:
B.shape

(3, 3)

In [65]:
#matrix multiplication
A=np.array(
    [
     [1,2,3],
     [4,5,6],
     [5,0,4]
    ]
)
B=np.array(
  [
    [7,8,6],
    [9,10,7],
    [11,12,8]
  ]
)
A*B

array([[ 7, 16, 18],
       [36, 50, 42],
       [55,  0, 32]])