Linear Algebra

In [1]:
import numpy as np
import sys

In [13]:
A=np.array(
    [
     [1,2,3],
     [4,5,6],
     [7,8,9]
    ]
)
B=np.array(
    [
     [10,11],
     [13,14],
     [16,0]
    ]
)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11]
 [13 14]
 [16  0]]


In [17]:
# A*B <- won't working even though i x j, j x k matrix
# solution :
A.dot(B)

array([[ 84,  39],
       [201, 114],
       [318, 189]])

In [19]:
# other way
A @ B

array([[ 84,  39],
       [201, 114],
       [318, 189]])

In [23]:
print(B)
print(B.T) # transpose of matrix

[[10 11]
 [13 14]
 [16  0]]
[[10 13 16]
 [11 14  0]]


In [24]:
B.T @ A

array([[174, 213, 252],
       [ 67,  92, 117]])

Size of Objects in memory

Int,Floats sizes in python vs. numpy

In [39]:
#python size
print(sys.getsizeof(1),"bytes")
print(sys.getsizeof(10**100),"bytes")
print(sys.getsizeof([1]),"bytes")

28 bytes
72 bytes
80 bytes


In [46]:
#numpy size
print(np.dtype(np.int64).itemsize)
print(np.dtype(np.float).itemsize)
print(np.dtype(list).itemsize)
print(np.array([1]).nbytes)

8
8
8
8


And Performance is also important

In [49]:
l=list(range(1000))

In [50]:
a=np.arange(1000)

In [51]:
%time np.sum(a**2)

CPU times: user 700 µs, sys: 0 ns, total: 700 µs
Wall time: 697 µs


332833500

In [52]:
%time sum([x**2 for x in l])

CPU times: user 449 µs, sys: 0 ns, total: 449 µs
Wall time: 453 µs


332833500

Useful Numpy functions

random

In [56]:
 np.random.random(size=2)

array([0.51945564, 0.59560312])

In [57]:
np.random.normal(size=2)

array([ 0.83678615, -0.94626246])

In [60]:
np.random.rand(2,4)

array([[0.50218857, 0.5908643 , 0.98670714, 0.71314587],
       [0.99372896, 0.16239101, 0.58937586, 0.96972989]])

arange

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [63]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [64]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.arange(10,19).reshape(3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

linspace

In [69]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [70]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros,ones,empty

In [74]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [76]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
np.empty((2,2),dtype=int)

array([[4598175219545276416, 4602678819172646912],
       [4604930618986332160, 4607182418800017408]])

identity & eye

In [85]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [88]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [90]:
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [96]:
"Hello World"[6]

'W'