Brodcasting and Vectorised Operations

In [12]:
import numpy as np
import sys

In [13]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [14]:
a+10
#will not affect a existing array returns new array

array([10, 11, 12, 13])

In [15]:
a*10

array([ 0, 10, 20, 30])

In [16]:
a

array([0, 1, 2, 3])

In [30]:
a+=100
a
#will effect on a as we given = i.e a=a+100

array([300, 301, 302, 303])

In [18]:
l=[0,1,2,3]

In [19]:
[i*10 for i in l]

[0, 10, 20, 30]

In [22]:
b=np.arange(4)

In [23]:
a+b

array([100, 102, 104, 106])

In [27]:
a*b.dtype

array([dtype(('<i8', (100,))), dtype(('<i8', (101,))),
       dtype(('<i8', (102,))), dtype(('<i8', (103,)))], dtype=object)

In [28]:
a.dtype

dtype('int64')

In [ ]:
b